# site properties and page defaults
title: C³N Lab
subtitle: Cognitive and Clinical Computational Neuroscience Laboratory
description:  Cognitive and Clinical Computational Neuroscience Laboratory, University of Tuebingen in Germany headed by Dr Stefanie Liebe
header: 
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@Muthu-JeyanthiDESCRIPTION=An engaging 1-3 sentence description of your lab..com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: Muthu-JeyanthiDESCRIPTION=An engaging 1-3 sentence description of your lab.
  twitter: Muthu-JeyanthiDESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: Muthu-JeyanthiDESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
