# site properties and page defaults
title:
subtitle:
description:  Cognitive and Clinical Computational Neuroscience Laboratory, University of Tuebingen in Germany headed by Dr Stefanie Liebe
header: images/blue_bg.jpg
footer: images/blue_bg.jpg
proofer: false

# site social media and other links
links:
  email: stefanie.liebe@uni-tuebingen.de
  orcid: https://orcid.org/0000-0003-2873-2943
  google-scholar: https://scholar.google.de/citations?user=38Sq-ZYAAAAJ&hl=en
  github: Muthu-JeyanthiDESCRIPTION=An engaging 1-3 sentence description of your lab.
  twitter: Muthu-JeyanthiDESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: Muthu-JeyanthiDESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
